#!/bin/bash
cd src
rm lambda.zip
zip -r lambda.zip *
aws apigateway put-rest-api --rest-api-id lxlwvoenil --mode overwrite --body file://res/api.json --profile personal
aws apigateway create-deployment --rest-api-id lxlwvoenil --stage-name prod --profile personal
aws lambda update-function-code --function-name TennisLadder --zip-file fileb://lambda.zip --profile personal
cd ..
